export const COUNTRY_LIST = [
  { value: "+91", label: "🇮🇳 +91 India" },
  { value: "+966", label: "🇸🇦 +966 Saudi Arabia" },
  { value: "+971", label: "🇦🇪 +971 UAE" },
  { value: "+965", label: "🇰🇼 +965 Kuwait" },
  { value: "+974", label: "🇶🇦 +974 Qatar" },
  { value: "+973", label: "🇧🇭 +973 Bahrain" },
  { value: "+968", label: "🇴🇲 +968 Oman" },
  { value: "+880", label: "🇧🇩 +880 Bangladesh" },
  { value: "+977", label: "🇳🇵 +977 Nepal" },
  { value: "+94", label: "🇱🇰 +94 Sri Lanka" },
  { value: "+95", label: "🇲🇲 +95 Myanmar" },
  { value: "+975", label: "🇧🇹 +975 Bhutan" },
  { value: "+92", label: "🇵🇰 +92 Pakistan" },
  { value: "+93", label: "🇦🇫 +93 Afghanistan" },
  { value: "+86", label: "🇨🇳 +86 China" },

  // Other important countries
  { value: "+1", label: "🇺🇸 +1 USA/Canada" },
  { value: "+44", label: "🇬🇧 +44 UK" },
  { value: "+49", label: "🇩🇪 +49 Germany" },
  { value: "+33", label: "🇫🇷 +33 France" },
  { value: "+39", label: "🇮🇹 +39 Italy" },
  { value: "+34", label: "🇪🇸 +34 Spain" },
  { value: "+31", label: "🇳🇱 +31 Netherlands" },
  { value: "+46", label: "🇸🇪 +46 Sweden" },
  { value: "+47", label: "🇳🇴 +47 Norway" },
  { value: "+45", label: "🇩🇰 +45 Denmark" },
  { value: "+358", label: "🇫🇮 +358 Finland" },
  { value: "+41", label: "🇨🇭 +41 Switzerland" },
  { value: "+43", label: "🇦🇹 +43 Austria" },
  { value: "+32", label: "🇧🇪 +32 Belgium" },
  { value: "+351", label: "🇵🇹 +351 Portugal" },
  { value: "+353", label: "🇮🇪 +353 Ireland" },
  { value: "+61", label: "🇦🇺 +61 Australia" },
  { value: "+64", label: "🇳🇿 +64 New Zealand" },
  { value: "+81", label: "🇯🇵 +81 Japan" },
  { value: "+82", label: "🇰🇷 +82 South Korea" },
  { value: "+65", label: "🇸🇬 +65 Singapore" },
  { value: "+60", label: "🇲🇾 +60 Malaysia" },
  { value: "+66", label: "🇹🇭 +66 Thailand" },
  { value: "+84", label: "🇻🇳 +84 Vietnam" },
  { value: "+62", label: "🇮🇩 +62 Indonesia" },
  { value: "+63", label: "🇵🇭 +63 Philippines" },
  { value: "+7", label: "🇷🇺 +7 Russia" },
  { value: "+380", label: "🇺🇦 +380 Ukraine" },
  { value: "+48", label: "🇵🇱 +48 Poland" },
  { value: "+420", label: "🇨🇿 +420 Czech Republic" },
  { value: "+36", label: "🇭🇺 +36 Hungary" },
  { value: "+40", label: "🇷🇴 +40 Romania" },
  { value: "+30", label: "🇬🇷 +30 Greece" },
  { value: "+90", label: "🇹🇷 +90 Turkey" },
  { value: "+52", label: "🇲🇽 +52 Mexico" },
  { value: "+55", label: "🇧🇷 +55 Brazil" },
  { value: "+54", label: "🇦🇷 +54 Argentina" },
  { value: "+56", label: "🇨🇱 +56 Chile" },
  { value: "+57", label: "🇨🇴 +57 Colombia" },
  { value: "+51", label: "🇵🇪 +51 Peru" },
  { value: "+58", label: "🇻🇪 +58 Venezuela" },
  { value: "+27", label: "🇿🇦 +27 South Africa" },
];
